# Numerical Computing with Numpy

In [11]:
w1,w2,w3=0.3,0.5,0.6

In [2]:
kanto_temp=73
kanto_rain=67
kanto_humidity=43

kanto_yield_apples=kanto_temp*w1+kanto_rain*w2+kanto_humidity*w3

kanto_yield_apples

81.2

In [12]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

weights=[w1,w2,w3]

In [13]:
#declare funciotn
def crop_yield(regin,weight):
    res=0
    for x,w in zip(regin,weight):
        res+=x*w
    return res

In [14]:
crop_yield(kanto,weights)

81.2

In [15]:
crop_yield(unova,weights)

110.7

In [19]:
!pip install numpy --upgrade --quiet

In [18]:
import numpy as np

In [20]:
kanto=np.array([32,11,13])

kanto

array([32, 11, 13])

In [21]:
weights=np.array([w1,w2,w3])
weights

array([0.3, 0.5, 0.6])

In [22]:
type(kanto)

numpy.ndarray

In [23]:
type(weights)

numpy.ndarray

In [24]:
weights[0]

0.3

In [25]:
kanto[2]

13

In [26]:
np.dot(kanto,weights)

22.9

In [37]:
(kanto*weights).sum()

22.9

In [28]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr1*arr2

array([ 4, 10, 18])

In [29]:
arr2.sum()

15

In [35]:
arr1=list(range(1000000))
arr2=list(range(1000000,2000000))
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

In [33]:
%%time
result=0
for x1,x2 in zip(arr1,arr2):
    result+=x1*x2
result

CPU times: total: 125 ms
Wall time: 230 ms


833332333333500000

In [38]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: total: 0 ns
Wall time: 2 ms


-1942957984

# Multi-dimensional Numpy arrays

In [39]:
climate_data=np.array([[2,1,3],
                      [2,5,8],
                      [20,245,3]])

In [40]:
climate_data

array([[  2,   1,   3],
       [  2,   5,   8],
       [ 20, 245,   3]])

In [41]:
climate_data.shape

(3, 3)

In [42]:
weights

array([0.3, 0.5, 0.6])

In [43]:
weights.shape

(3,)

In [44]:
arr3=np.array([[[11,2,3],[12,3,56]],[[233,46,22],[23,456,18.9]]])

arr3.shape

(2, 2, 3)

In [45]:
weights.dtype

dtype('float64')

In [46]:
climate_data.dtype

dtype('int32')

In [47]:
arr3.dtype

dtype('float64')

In [48]:
np.matmul(climate_data,weights)

array([  2.9,   7.9, 130.3])

In [49]:
climate_data @ weights

array([  2.9,   7.9, 130.3])

In [50]:
import urllib.request

import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x2223b438dd0>)

In [51]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [53]:
climate_data.shape

(10000, 3)

In [55]:
yields=climate_data @ weights

In [56]:
yields

array([104.9,  86.2,  86.4, ...,  95.5, 111.1,  92.7])

In [57]:
yields

array([104.9,  86.2,  86.4, ...,  95.5, 111.1,  92.7])

In [58]:
yields.shape

(10000,)

In [59]:
climate_result=np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

climate_result

array([[ 25. ,  76. ,  99. , 104.9],
       [ 39. ,  65. ,  70. ,  86.2],
       [ 59. ,  45. ,  77. ,  86.4],
       ...,
       [ 99. ,  62. ,  58. ,  95.5],
       [ 70. ,  71. ,  91. , 111.1],
       [ 92. ,  39. ,  76. ,  92.7]])

In [61]:
np.savetxt('climate_result.txt',climate_result,fmt='%.2f',delimiter=',',header='temperature,rainfall,humidity,yeild_apples',comments='')

# Arithmetic operation,broadcasting and comparison


In [63]:
arr2=np.array([[1,35,6],[22,2,1]])
arr3=np.array([[2234,45,6],[34,5465,2]])



In [65]:
#Adding a scalar 
arr2+43

array([[44, 78, 49],
       [65, 45, 44]])

In [66]:
#Element wise subtraction
arr3-arr2

array([[2233,   10,    0],
       [  12, 5463,    1]])

In [67]:
#Division by scalar
arr2/2


array([[ 0.5, 17.5,  3. ],
       [11. ,  1. ,  0.5]])

In [68]:
arr2*arr3

array([[ 2234,  1575,    36],
       [  748, 10930,     2]])

# Array  Comparison

In [69]:
arr2==arr3

array([[False, False,  True],
       [False, False, False]])

In [70]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])

In [71]:
arr1!=arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [72]:
arr1>=arr2

array([[ True, False, False],
       [False,  True,  True]])

In [73]:
(arr1==arr2).sum()

1

# Array indexing and slicing

In [74]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [76]:
arr3.shape

(3, 2, 4)

In [77]:
#single element
arr3[1,1,2]

36.0

In [78]:
#subarray using ranges
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

# Other ways of creating Numpy arrays

In [79]:
#all zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [80]:
#all ones
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [81]:
#identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
np.random.rand(5)#random vector

array([0.71894167, 0.30920619, 0.85853267, 0.45204808, 0.45599762])

In [84]:
np.random.randn(2,3)#random matrix

array([[-1.08168387, -1.76835036, -1.58872015],
       [-0.31172095,  0.34641013, -0.33147284]])

In [85]:
#fixed value assign
np.full([2,3],100)

array([[100, 100, 100],
       [100, 100, 100]])

In [86]:
np.arange(10,90,3)#rand with start,end and step

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [88]:
np.linspace(3,27,9) #Equally spaced number in a range

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])